### PR TITLE
Tenant view changes

### PR DESCRIPTION
**Pull request by arpiagariu**

### CODE REVIEW

**Comment by teone** [comment]
@arpiagariu some notes:
- 4 tests are failing
- the branch has conflicts
- TenantView is not tested

**Comment by teone** [comment]
@arpiagariu you need to rebuild the `ngXosHelpers.js` file. To do that go in `xos/views/ngXosLib

**Comment by arpiagariu** [comment]
Hi @teone : I am still not able to see the test failing in tenant view . I am just getting the following error:

Error{message: 'Unexpected request: GET /api/core/sites/?no_hyperlinks=1
No more request expected', line: 1245, sourceId: 80419600, sourceURL: 'http://localhost:9876/base/src/vendor/angular-mocks/angular-mock                                                                                                                                        s.js?f7cd2e8b3f5354e6ba7252e623167526d0d3733b', stack: 'Error: Unexpected request: GET /api/core/sites/?no_hyperlinks=1
No more request expected
    at $httpBackend (http://localhost:9876/base/src/vendor/angular-mocks/angular-mocks.js?f7cd2e8b3f5354e6ba7252e623167526d0d3733b:1245                                                                                                                                        )

**Comment by teone** [comment]
@arpiagariu the reason for that failing in `npm run test:ci` is in `xos/views/ngXosLib/karma.conf.ci.js` on line 22: `.filter(f => f.indexOf('xosTenant') === -1)` this was to prevent loading an old backbone based view, we can remove that line now.

**Comment by arpiagariu** [comment]
@teone Please check once, I removed that line

**Pull request merged**
